---
agent_namespace: devops

agent_workdir: /usr/mware/agent/_work

agent_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66316365653831613531623562306663393136616438333335633436633137323065396563376532
  3737343737303733643562306362626630346430613338310a316365336233303165306463383430
  37636231633632383061613761623137383132373865303538393230353236336530363934383361
  3865313965333665650a333364633961333237623339663066356534316134323731346435333763
  37663866616237646639383962363431353933393530383333393935346534393265393065323633
  30373933336630386634643035636135336436373730363432623038613461353261306337353937
  34663266663734663062666362666632356530386465336563343734386161373665363435356466
  38396165616234666164326537616139366531386336666331636130343030623238643039366363
  3938

agent_healthcheck_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38386332323361653530653036346537376536396265653561383831306332363938666431353461
  6134636138363536306339323066393063353831373966360a313666373139373537623766333163
  64653331343762346262313936653862326265383963623539636465316331666365366434326337
  3933376136656435360a636632616665663133323635656661663563663166383266376661666462
  39363066333539346537333766303831333631666262666438346365653866653533373932333464
  34363333383036633931383430636236356531373537343163656365613061356238653563656530
  37346238353531653030373333323034303839656632383136336365656462326437663266366464
  37356535613365353230643433313765653032613265623833633836306666626166653932393561
  3863
