---
agent_namespace: devops

agent_workdir: /usr/mware/agent/_work

agent_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36653863346139386163373535613665653932656261303463303933343235623233363534646134
  6636316337323633656236323831366438326538373564640a393233623232626238613834626363
  38663835666264613638323864653562633439623261353439313063623232363839643331613036
  6339316432323137310a376365613162376461646231636464656161613633633036386634323730
  61376234326235623764626664336338336465633838353439643831633135343961666165313432
  32303332666332663364393638313066336436663434633462323936623030626332313164613965
  33616437613063366163626433643134336163653766663536383935666137623430393834353237
  66393665643931323266653061653665623038376338383530333730373061306532633661373237
  3331

agent_healthcheck_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62663239616231643630656562643231313439383637643233363735376336366635343433383434
  6338306537373063383139346531396465643438653638630a316433663833383731306263626231
  33333962373038663437666262323335623037313831613666343564333538636531613366393830
  6236353161653439610a636564653239376336303737323362656634646662313962396137343464
  65386562643033636236656366396166303836346165306666363866656538613062396331626137
  34663663623138633633653632623935656136626139623936613530653530626464643632613365
  39646531326235643166323832303136613966366332623161343737643339326330633433393731
  63616133363431656238363961663235306264386665346433656239643437363161333237613363
  3361
