# This is a basic workflow to help you get started with Actions

name: Deploy Latest
permissions:
  contents: read
  pull-requests: read
  issues: write

# Controls when the workflow will run
on:
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/latest.yml
      - roles/deploy/**
      - deploy.yml

env:
  DOCKER_REPOSITORY: coffee206/github-actions
  BUILD_DIR: builder
  STATEFUL_SET_NAME: builder

jobs:
  versioning:
    runs-on:
      - self-hosted
      - ansible
    outputs:
      x64_tag: x64-builder-latest
      arm64_tag: arm64-builder-latest
      common_tag: builder-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: espresso-software/actions/common/versioning@main
        id: get_version
        with:
          version_file: builder/version.json

  uat-deploy:
    needs: 
      - versioning
    runs-on:
      - self-hosted
      - ansible
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - name: Cleanup uat
        uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: cleanup.yml
          inventory_path: inventory/hosts.ini
          vars: stateful_set_name=uat-${{ env.STATEFUL_SET_NAME }}
      - name: Install docker
        uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: docker.yml
          inventory_path: inventory/hosts.ini
      - name: Deploy x64 image
        uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy.yml
          inventory_path: inventory/hosts.ini
          vars: stateful_set_name=uat-${{ env.STATEFUL_SET_NAME }} tag=${{ needs.versioning.outputs.x64_tag }} arch=amd64 labels=uat
  
  uat-cleanup:
    needs:
      - uat-deploy
    runs-on:
      - self-hosted
      - ansible
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: cleanup.yml
          inventory_path: inventory/hosts.ini
          vars: stateful_set_name=uat-${{ env.STATEFUL_SET_NAME }}

  deploy:
    needs: 
      - versioning
      - uat-deploy
    runs-on:
      - self-hosted
      - ansible
    env:
      COMMON_ARGS: tag=${{ needs.versioning.outputs.common_tag }} cpu_limits=2000m mem_limits=4Gi mem_requests=512Mi
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.READ_ACCESS_TOKEN }}
      - name: Arm64 deploy
        uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy.yml
          inventory_path: inventory/hosts.ini
          vars: stateful_set_name=arm64-${{ env.STATEFUL_SET_NAME }} arch=arm64 replicas=2 ${{ env.COMMON_ARGS }} 
      - name: x64 deploy
        uses: espresso-software/actions/ansible/run-playbook@main
        env:
          VAULT_DECRYPT_TOKEN: ${{ secrets.VAULT_DECRYPT_TOKEN }}
        with:
          playbook_path: deploy.yml
          inventory_path: inventory/hosts.ini
          vars: stateful_set_name=x64-${{ env.STATEFUL_SET_NAME }} arch=amd64 replicas=2 ${{ env.COMMON_ARGS }}